analytics: {}
color:
  brandColors:
    - '#000000'
    - '#261100'
    - '#7D5C29'
    - '#AC8A65'
    - '#B87737'
  brandStrength: 0.828125
  lightness: 0.90767
  rhythmicContrast: 0.951705
  saturation: 0.784091
cta: {}
layout_spectrum: 0.9749598470516503
name: One School
opengraph: {}
purpose: []
typography_spectrum: 0.841794608393684
